language: php

php:
  - 7.2
  - 7.3

dist: xenial

services:
  - mysql

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction
  - mysql -e "create database IF NOT EXISTS testing;" -uroot;

script:
  - vendor/bin/phpunit
